# Generated by Django 6.0.2 on 2026-03-02 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('movement_type', models.CharField(choices=[('INCOME', 'Приход'), ('OUTGO', 'Расход')], default='INCOME', max_length=10, verbose_name='Тип операции')),
                ('reason', models.TextField(verbose_name='Причины')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник/Назначение')),
                ('created_at', models.DateField()),
            ],
            options={
                'verbose_name': 'Денежное движение',
                'verbose_name_plural': 'Денежные движения',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('supplier', 'Поставщик'), ('customer', 'Клиент')], max_length=10, verbose_name='Тип контакта')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ФИО или Организация')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('postav', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('count', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Postav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postav', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('total_cen', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Prodaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('prod_date', models.DateField()),
                ('cen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('count', models.SmallIntegerField()),
                ('prod_form', models.TextField(max_length=20)),
                ('zakaz_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('prih_cen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prih_date', models.DateField()),
                ('count', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('opl_date', models.DateField()),
                ('vznos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('m_count', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostavCashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('movement_type', models.CharField(choices=[('INCOME', 'Приход'), ('OUTGO', 'Расход')], default='INCOME', max_length=10)),
                ('reason', models.TextField(verbose_name='Причины')),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField()),
                ('postav_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.postav')),
            ],
        ),
        migrations.CreateModel(
            name='PostavProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('cen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('count', models.SmallIntegerField()),
                ('prih', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('postav_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.postav')),
            ],
        ),
        migrations.CreateModel(
            name='ZakazProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('cen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('count', models.SmallIntegerField()),
                ('zakaz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.zakaz')),
            ],
        ),
    ]
